### ISSUE TITLE
When uploading, include maven-metadata.xml

### ISSUE THREAD

**Issue by BrainStone** [simpligility/maven-repository-tools#34]
I'm currently trying to migrate my old maven repo to my new nexus repo, but when uploading it from local cache (using `-cd`) all artifacts get uploaded just fine. But no `maven-metadata.xml` is uploaded.

Also a quick question, can I delete the `md5` and `sha1` checksum files before I upload?

**Comment by mosabua** [comment]
The maven metadata file should NOT be uploaded by design as it is specific to the local repository or source repo. The target repo manager has to be able to fix it based on its content .. 

And the md5 and sha1 files can be deleted or kept .. either is fine but should probably be kept.
