### ISSUE TITLE
Don't include md5 or sha1 when migrating from FS

### ISSUE THREAD

**Issue by Secathor** [simpligility/maven-repository-tools#35]
Hi,
When migrating a Nexus2 repository (from `sonatype-work/storage/my-repo` directory) to a new Nexus3, the script complains about checksum files

```
WARN  o.e.a.c.b.BasicRepositoryConnector - Failed to upload checksum groupId/artifactId/1.0.0/artifactId-1.0.0-classifier.ext.md5.sha1: Server Error (500)
WARN  o.e.a.c.b.BasicRepositoryConnector - Failed to upload checksum groupId/artifactId/1.0.0/artifactId-1.0.0-classifier.ext.md5.md5: Server Error (500)
```

BTW, thx a lot for this such convenient tool !

**Comment by mosabua** [comment]
Why is that invalid? Seems more like a Nexus3 bug to be honest.

**Comment by Secathor** [comment]
I suspect the tool to upload checksums of checksum file ;-)

```
Failed to upload checksum <path>/<file>.md5.sha1
Failed to upload checksum <path>/<file>.md5.md5
```

**Comment by mosabua** [comment]
Oh... hm. How did those files even get into the repo? Those are invalid content ..

**Comment by Secathor** [comment]
Mmmh right...
I've deleted the old repo so I can't check if hash-hash files comes from there.
Maybe Nexus 2 don't complains about receiving those kind of files, and Nexus 3 don't want them.

Let's close this issue and reopen if this happens again.
