### ISSUE TITLE
Wrong classpath entry in manifest

### ISSUE THREAD

**Issue by joehni** [simpligility/maven-repository-tools#44]
Hi,

when generating the maven-repository-provisioner-*-jar-with-dependencies.jar you add the classpath of all dependencies to the manifest, but this is wrong. Either you use the dependency plugin to collect all jars - then the classpath entry in the manifest must match the (relative) location to this collection - or you drop the classpath entry, since you currently merge all classes together in one big jar.

Cheers,
Jörg

**Comment by mosabua** [comment]
Fair point. I will drop the classpath .. probably in the work towards the next release in the next week or two (hopefully). A PR would also be appreciated ;-)

**Comment by joehni** [comment]
C'mon, it's a single line:

```diff
diff --git a/maven-repository-provisioner/pom.xml b/maven-repository-provisioner/pom.xml
index 4ade433..7376c81 100644
--- a/maven-repository-provisioner/pom.xml
+++ b/maven-repository-provisioner/pom.xml
@@ -120,7 +120,6 @@
           <archive>
             <index>true</index>
             <manifest>
-              <addClasspath>true</addClasspath>
               <mainClass>com.simpligility.maven.provisioner.MavenRepositoryProvisioner</mainClass>
             </manifest>
           </archive>
```
:-D

**Comment by mosabua** [comment]
thx .. I guess you beat me to it.
