### ISSUE TITLE
Filter support for the deployer

### ISSUE THREAD

**Issue by dakaneye** [simpligility/maven-repository-tools#81]
**Problem**
There are some use cases for being able to control what actually gets deployed to the maven repository. Mostly controlling the content of the repository being deployed to.

**Solution**
Add support for a filter file, to be passed in through configuration. 
The filter file would contain a GAV per line, and would dictate what can be deployed (anything not in the file won't get deployed).
Example: 
```
org.apache.maven.resolver:maven-resolver-transport-file:1.9.22:jar
org.apache.maven:maven-compat:3.9.9:jar
com.google.guava:failureaccess:1.0.2:jar
org.fusesource.jansi:jansi:2.4.1:jar
org.slf4j:slf4j-api:1.7.36:jar
```
If the file didn't exist or the configuration wasn't specified, we wouldn't filter what gets deployed (current logic).

**Comment by mosabua** [comment]
I think thats good but it would really need to be more powerful and allow pattern matching

Examples:

Exclude a project

```
org.apache.maven.resolver:*:*:*
org.apache.maven:*:*:*
```

Exclude a company namespace

```
com.simpligility:*:*:*
```

Those are easy .. it gets more tricky if we should allow pattern for a coordinate

```
org.apach.foo-*:*:*:*
```

Not sure if that is useful .. we could do that later

Same applies for filtering on packages

```
*:*:*:sources
```

to never deploy sources or javadoc:

or 

```
*:*:*:javadoc
```
