### ISSUE TITLE
Fix requirements in readme

### ISSUE THREAD

**Issue by SebastianFlothow** [simpligility/maven-repository-tools#85]
Both READMEs (the main one and the one in subdir maven-repository-provisioner) state that Java 11 is required. However, maven-repository-provisioner-1.5.1-jar-with-dependencies.jar contains classes using class file version 61.0, so actually Java 17 is required.

**Comment by mosabua** [comment]
Want to send a PR to update the docs and check the build?

**Comment by mosabua** [comment]
Fixed

**Comment by mosabua** [comment]
Sorry btw.. I am using Java 23 so never found the problem.
